package com.zslab.mall.audit.repository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.zslab.mall.Batch1DataJpaTestBase;
import com.zslab.mall.audit.entity.AuditLog;
import com.zslab.mall.audit.enums.AuditLogAction;
import com.zslab.mall.common.enums.PolymorphicTargetType;
import jakarta.persistence.PersistenceException;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * {@link AuditLogRepository} @DataJpaTest — CRUD·append-only 확인·publicId @PrePersist·LT-01·diff_json JSON.
 */
class AuditLogRepositoryTest extends Batch1DataJpaTestBase {

    @Autowired
    private AuditLogRepository auditLogRepository;

    @Test
    @DisplayName("save+findByPublicId 성공: action·targetType·targetId·publicId aud_ 확인")
    void save_findByPublicId_success() {
        AuditLog saved = auditLogRepository.saveAndFlush(
            AuditLog.create(1L, "ADMIN", AuditLogAction.CREATE,
                PolymorphicTargetType.PRODUCT, 100L, null, "127.0.0.1", "TestAgent"));
        entityManager.clear();

        Optional<AuditLog> found = auditLogRepository.findByPublicId(saved.getPublicId());

        assertThat(found).isPresent();
        assertThat(found.get().getAction()).isEqualTo(AuditLogAction.CREATE);
        assertThat(found.get().getTargetType()).isEqualTo(PolymorphicTargetType.PRODUCT);
        assertThat(found.get().getTargetId()).isEqualTo(100L);
        assertThat(found.get().getActorUserId()).isEqualTo(1L);
        assertThat(found.get().getCreatedAt()).isNotNull();
    }

    @Test
    @DisplayName("LT-01 검증: publicId @PrePersist 자동 발급·aud_ prefix·CHAR(30) 30자 확인")
    void publicId_autogenerated_isThirtyCharsWithAudPrefix() {
        AuditLog saved = auditLogRepository.saveAndFlush(
            AuditLog.create(null, null, AuditLogAction.LOGIN,
                PolymorphicTargetType.USER, 1L, null, null, null));

        assertThat(saved.getPublicId()).isNotNull();
        assertThat(saved.getPublicId()).hasSize(30);
        assertThat(saved.getPublicId()).startsWith("aud_");
    }

    @Test
    @DisplayName("diff_json JSON 저장: DDL CHECK(JSON_VALID) 통과·String 매핑 정합 확인")
    void save_diffJson_jsonStringStored() {
        String diffJson = "{\"name\":{\"before\":\"구 이름\",\"after\":\"신 이름\"}}";
        AuditLog saved = auditLogRepository.saveAndFlush(
            AuditLog.create(1L, "SELLER", AuditLogAction.UPDATE,
                PolymorphicTargetType.PRODUCT, 200L, diffJson, null, null));
        entityManager.clear();

        Optional<AuditLog> found = auditLogRepository.findById(saved.getId());

        assertThat(found).isPresent();
        assertThat(found.get().getDiffJson()).isEqualTo(diffJson);
    }

    @Test
    @DisplayName("diff_json 비유효 JSON 삽입 → PersistenceException (DDL CHECK JSON_VALID)")
    void insert_invalidDiffJson_throwsPersistenceException() {
        assertThatThrownBy(() ->
            entityManager.getEntityManager().createNativeQuery(
                "INSERT INTO audit_log (public_id, action, target_type, target_id, diff_json, created_at) "
                + "VALUES ('aud_chk01234567890123456789012', 'CREATE', 'PRODUCT', 1, 'NOT_JSON', NOW(6))")
                .executeUpdate()
        ).isInstanceOf(PersistenceException.class);
    }

    @Test
    @DisplayName("findByTargetTypeAndTargetId: polymorphic 조회 목록 반환")
    void findByTargetTypeAndTargetId_success() {
        auditLogRepository.saveAndFlush(
            AuditLog.create(1L, "ADMIN", AuditLogAction.CREATE,
                PolymorphicTargetType.ORDER, 50L, null, null, null));
        auditLogRepository.saveAndFlush(
            AuditLog.create(2L, "ADMIN", AuditLogAction.UPDATE,
                PolymorphicTargetType.ORDER, 50L, null, null, null));
        auditLogRepository.saveAndFlush(
            AuditLog.create(1L, "ADMIN", AuditLogAction.DELETE,
                PolymorphicTargetType.PRODUCT, 50L, null, null, null));
        entityManager.clear();

        List<AuditLog> results = auditLogRepository
            .findByTargetTypeAndTargetId(PolymorphicTargetType.ORDER, 50L);

        assertThat(results).hasSize(2);
    }

    @Test
    @DisplayName("action ENUM 외 값 삽입 → PersistenceException (ENUM constraint)")
    void insert_invalidAction_throwsPersistenceException() {
        assertThatThrownBy(() ->
            entityManager.getEntityManager().createNativeQuery(
                "INSERT INTO audit_log (public_id, action, target_type, target_id, created_at) "
                + "VALUES ('aud_enu01234567890123456789012', 'INVALID_ACTION', 'PRODUCT', 1, NOW(6))")
                .executeUpdate()
        ).isInstanceOf(PersistenceException.class);
    }
}
